name: simulation
root: ./
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=x500; export WORLD_NAME=simulation; export SENSORS="garmin_down"
startup_window: status
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch laser_challenge_simulation stage_four.launch world_name:=stage_four gui:=true
        - waitForOdometry; gz camera -c gzclient_camera -f ${UAV_NAME}; history -s gz camera -c gzclient_camera -f ${UAV_NAME}
  - status:
      layout: tiled
      panes:
        - waitForSimulation; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: tiled
      panes:
        - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 $UAV_TYPE --enable-rangefinder --enable-bluefox-camera --enable-realsense-down --enable-ground-truth --enable-realsense-front --enable-rplidar --pos_file `pwd`/pos.yaml"
  - control:
      layout: tiled
      panes:
        - waitForOdometry; roslaunch mrs_uav_general core.launch
  - takeoff:
      layout: tiled
      panes:
        - waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - 'waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          sleep 2;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
  - goto:
      layout: tiled
      panes:
        - 'waitForControl; sleep 20; rosservice call /$UAV_NAME/control_manager/goto "goal: [5.0, 5.0, 2.0, 3.1415]"'
  - lp_detection:
      layout: tiled
      panes:
        - waitForControl; roslaunch laser_vision lp_detector.launch
        - waitForControl; sleep 25; python ../../scripts/base_following.py
  # - rviz:
  #     layout: tiled
  #     panes:
  #       - waitForControl; roslaunch mrs_uav_testing rviz_random_simulation.launch
  #       - waitForControl; roslaunch mrs_rviz_plugins load_robot.launch
  # - easy_control:
  #     layout: tiled
  #     panes:
  #       - waitForControl; waitForControl; roslaunch mrs_uav_general logitech_joystick.launch
  #       - waitForControl; waitForControl; roslaunch mrs_rviz_plugins rviz_interface.launch
  # - layout:
  #     layout: tiled
  #     panes:
  #       - waitForControl; sleep 3; ~/.i3/layout_manager.sh ./layout.json
